// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

const defaultDatabaseUrl =
  "sqlserver://localhost:1433;database=mycrm;user=sa;password=LocalPassword!23;encrypt=false;trustServerCertificate=true";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? defaultDatabaseUrl,
  },
});
