import type {
  AccountSite,
  AccountSummary,
  Contact,
  SalesCondition,
} from "~/lib/domain/entities/account";
import type { ActivitySummary } from "~/lib/domain/entities/activity";
import type { OpportunitySummary } from "~/lib/domain/entities/opportunity";
import type { ProductCatalogItem } from "~/lib/domain/entities/product";

export const demoProducts: ProductCatalogItem[] = [
  {
    id: "prod-granola",
    name: "朝食グラノーラ 400g",
    category: "シリアル",
    temperatureZone: "ambient",
    shelfLifeDays: 270,
    packSize: "12袋 / ケース",
    marginBand: "A",
    targetChannels: ["retail", "wholesale", "ecommerce"],
    basePrice: 468,
  },
  {
    id: "prod-soup",
    name: "濃厚ポタージュ 180g",
    category: "即食スープ",
    temperatureZone: "ambient",
    shelfLifeDays: 365,
    packSize: "24袋 / ケース",
    marginBand: "B",
    targetChannels: ["retail", "wholesale", "foodservice"],
    basePrice: 258,
  },
  {
    id: "prod-gyoza",
    name: "冷凍野菜餃子 24個",
    category: "冷凍惣菜",
    temperatureZone: "frozen",
    shelfLifeDays: 365,
    packSize: "10袋 / ケース",
    marginBand: "A",
    targetChannels: ["retail", "wholesale", "foodservice"],
    basePrice: 598,
  },
  {
    id: "prod-dressing",
    name: "業務用ごまドレッシング 1L",
    category: "調味料",
    temperatureZone: "ambient",
    shelfLifeDays: 240,
    packSize: "6本 / ケース",
    marginBand: "S",
    targetChannels: ["wholesale", "foodservice", "distributor"],
    basePrice: 780,
  },
  {
    id: "prod-smoothie",
    name: "冷蔵フルーツスムージー 250ml",
    category: "チルド飲料",
    temperatureZone: "chilled",
    shelfLifeDays: 21,
    packSize: "20本 / ケース",
    marginBand: "B",
    targetChannels: ["retail", "ecommerce"],
    basePrice: 238,
  },
];

export const demoAccounts: AccountSummary[] = [
  {
    id: "acct-aeon",
    name: "イオンリテール株式会社",
    channel: "retail",
    region: "首都圏",
    segment: "GMS",
    health: "healthy",
    annualRevenue: 180000000,
    summary: "本部商談で朝食商材の棚拡大が進行中。冷凍惣菜は東日本 120 店舗で追加導入余地あり。",
    nextAction: "4月棚替え前に冷凍餃子の試食提案をバイヤーへ提出",
    lastContactAt: "2026-03-08",
    currentProductNames: ["朝食グラノーラ 400g", "濃厚ポタージュ 180g"],
    whitespaceProductNames: ["冷凍野菜餃子 24個", "冷蔵フルーツスムージー 250ml"],
  },
  {
    id: "acct-kokubu",
    name: "国分グループ本社株式会社",
    channel: "wholesale",
    region: "全国",
    segment: "食品卸",
    health: "healthy",
    annualRevenue: 230000000,
    summary: "量販向けの帳合は安定。業務用ドレッシングを外食チェーン向けに横展開したい。",
    nextAction: "業務用向け値引き条件の試算を営業企画と確認",
    lastContactAt: "2026-03-05",
    currentProductNames: ["濃厚ポタージュ 180g", "業務用ごまドレッシング 1L"],
    whitespaceProductNames: ["冷凍野菜餃子 24個"],
  },
  {
    id: "acct-lawson",
    name: "株式会社ローソン",
    channel: "retail",
    region: "全国",
    segment: "CVS",
    health: "watch",
    annualRevenue: 92000000,
    summary: "チルド飲料のテスト導入評価は良好だが、粗利条件の調整が継続中。",
    nextAction: "新価格案と販促協賛比率を提示",
    lastContactAt: "2026-02-28",
    currentProductNames: ["冷蔵フルーツスムージー 250ml"],
    whitespaceProductNames: ["朝食グラノーラ 400g", "濃厚ポタージュ 180g"],
  },
  {
    id: "acct-rakuten",
    name: "楽天マート株式会社",
    channel: "ecommerce",
    region: "関東",
    segment: "ネットスーパー",
    health: "risk",
    annualRevenue: 46000000,
    summary: "EC 向けまとめ買い企画が弱く、リピート率が低下。定番 SKU の再編が必要。",
    nextAction: "セット提案とレビュー改善施策を提出",
    lastContactAt: "2026-02-18",
    currentProductNames: ["朝食グラノーラ 400g"],
    whitespaceProductNames: ["濃厚ポタージュ 180g", "冷蔵フルーツスムージー 250ml"],
  },
  {
    id: "acct-skylark",
    name: "株式会社すかいらーくレストランツ",
    channel: "foodservice",
    region: "全国",
    segment: "外食チェーン",
    health: "watch",
    annualRevenue: 76000000,
    summary: "ランチ帯のスープ差し替え提案が継続。厨房オペレーション適合の確認待ち。",
    nextAction: "調理負荷検証結果を共有し、業務用ドレッシング併売提案を実施",
    lastContactAt: "2026-03-01",
    currentProductNames: ["濃厚ポタージュ 180g"],
    whitespaceProductNames: ["業務用ごまドレッシング 1L", "冷凍野菜餃子 24個"],
  },
];

export const demoSites: Record<string, AccountSite[]> = {
  "acct-aeon": [
    {
      id: "site-aeon-kanto",
      name: "首都圏 GMS 120 店舗",
      prefecture: "東京・神奈川・千葉",
      format: "GMS",
      monthlyVolume: 24000,
      installedSkus: 2,
    },
    {
      id: "site-aeon-east",
      name: "東日本 SM 80 店舗",
      prefecture: "埼玉・群馬・栃木",
      format: "SM",
      monthlyVolume: 9600,
      installedSkus: 1,
    },
  ],
  "acct-kokubu": [
    {
      id: "site-kokubu-hq",
      name: "広域量販本部",
      prefecture: "東京",
      format: "卸本部",
      monthlyVolume: 32000,
      installedSkus: 2,
    },
  ],
  "acct-lawson": [
    {
      id: "site-lawson-kanto",
      name: "関東テスト 300 店舗",
      prefecture: "東京・神奈川",
      format: "CVS",
      monthlyVolume: 15000,
      installedSkus: 1,
    },
  ],
  "acct-rakuten": [
    {
      id: "site-rakuten-online",
      name: "ネットスーパー本部",
      prefecture: "東京",
      format: "EC",
      monthlyVolume: 4800,
      installedSkus: 1,
    },
  ],
  "acct-skylark": [
    {
      id: "site-skylark-east",
      name: "東日本 250 店舗",
      prefecture: "関東・東海",
      format: "外食チェーン",
      monthlyVolume: 21000,
      installedSkus: 1,
    },
  ],
};

export const demoContacts: Record<string, Contact[]> = {
  "acct-aeon": [
    {
      id: "contact-aeon-buyer",
      name: "高橋 由美",
      role: "バイヤー",
      department: "グロサリー商品部",
      email: "y.takahashi@example.com",
      phone: "03-1111-0001",
      influence: "decision-maker",
    },
    {
      id: "contact-aeon-store",
      name: "田中 誠",
      role: "販促責任者",
      department: "営業企画",
      influence: "champion",
    },
  ],
  "acct-kokubu": [
    {
      id: "contact-kokubu-md",
      name: "松本 隆",
      role: "MD 担当",
      department: "惣菜カテゴリー",
      influence: "decision-maker",
    },
  ],
  "acct-lawson": [
    {
      id: "contact-lawson-buyer",
      name: "伊藤 香織",
      role: "CVS バイヤー",
      department: "チルド・デイリー",
      influence: "decision-maker",
    },
  ],
  "acct-rakuten": [
    {
      id: "contact-rakuten-ec",
      name: "吉田 優斗",
      role: "カテゴリマネージャー",
      department: "EC 食品",
      influence: "champion",
    },
  ],
  "acct-skylark": [
    {
      id: "contact-skylark-chef",
      name: "小林 直樹",
      role: "メニュー開発責任者",
      department: "商品本部",
      influence: "operator",
    },
  ],
};

export const demoSalesConditions: Record<string, SalesCondition> = {
  "acct-aeon": {
    paymentTerms: "月末締め翌々月 5 日",
    rebateRate: 2.5,
    leadTimeDays: 5,
    minimumOrderValue: 180000,
    logisticsMode: "センター納品",
    promotionBudgetRatio: 4,
  },
  "acct-kokubu": {
    paymentTerms: "月末締め翌月末",
    rebateRate: 1.8,
    leadTimeDays: 3,
    minimumOrderValue: 250000,
    logisticsMode: "卸 DC 納品",
    promotionBudgetRatio: 2,
  },
  "acct-lawson": {
    paymentTerms: "月末締め翌月末",
    rebateRate: 4.2,
    leadTimeDays: 4,
    minimumOrderValue: 120000,
    logisticsMode: "共同配送",
    promotionBudgetRatio: 6,
  },
  "acct-rakuten": {
    paymentTerms: "月末締め翌月末",
    rebateRate: 3.5,
    leadTimeDays: 2,
    minimumOrderValue: 80000,
    logisticsMode: "EC 専用倉庫",
    promotionBudgetRatio: 5,
  },
  "acct-skylark": {
    paymentTerms: "月末締め翌々月 10 日",
    rebateRate: 2,
    leadTimeDays: 7,
    minimumOrderValue: 300000,
    logisticsMode: "厨房直送",
    promotionBudgetRatio: 3,
  },
};

export const demoOpportunities: OpportunitySummary[] = [
  {
    id: "opp-aeon-gyoza",
    accountId: "acct-aeon",
    accountName: "イオンリテール株式会社",
    channel: "retail",
    title: "冷凍野菜餃子 春棚替え導入",
    stage: "negotiation",
    probability: 70,
    expectedMonthlyRevenue: 6800000,
    targetCloseMonth: "2026-04",
    owner: "東日本第1営業部",
    blockers: ["販促協賛比率", "チラシ掲載可否"],
    nextStep: "4月1週の棚割り会議へ試食結果を持ち込む",
    productIds: ["prod-gyoza"],
  },
  {
    id: "opp-kokubu-dressing",
    accountId: "acct-kokubu",
    accountName: "国分グループ本社株式会社",
    channel: "wholesale",
    title: "外食チャネル向け 1L ドレッシング横展開",
    stage: "proposal",
    probability: 55,
    expectedMonthlyRevenue: 4200000,
    targetCloseMonth: "2026-05",
    owner: "広域卸営業部",
    blockers: ["卸リベート再設計"],
    nextStep: "粗利シミュレーションを企画へ共有",
    productIds: ["prod-dressing"],
  },
  {
    id: "opp-lawson-granola",
    accountId: "acct-lawson",
    accountName: "株式会社ローソン",
    channel: "retail",
    title: "朝食グラノーラ CVS 限定パッケージ",
    stage: "pilot",
    probability: 65,
    expectedMonthlyRevenue: 3100000,
    targetCloseMonth: "2026-06",
    owner: "CVS 営業チーム",
    blockers: ["店頭販促物の制作リードタイム"],
    nextStep: "テスト店舗 50 店の売れ筋レポートを提出",
    productIds: ["prod-granola"],
  },
  {
    id: "opp-rakuten-soup",
    accountId: "acct-rakuten",
    accountName: "楽天マート株式会社",
    channel: "ecommerce",
    title: "スープ・スムージー同梱セット改善",
    stage: "target",
    probability: 30,
    expectedMonthlyRevenue: 1700000,
    targetCloseMonth: "2026-05",
    owner: "EC 営業チーム",
    blockers: ["レビュー件数不足", "広告原資不足"],
    nextStep: "訴求軸別の LP 案を作成",
    productIds: ["prod-soup", "prod-smoothie"],
  },
  {
    id: "opp-skylark-dressing",
    accountId: "acct-skylark",
    accountName: "株式会社すかいらーくレストランツ",
    channel: "foodservice",
    title: "業務用ドレッシングとスープのセット採用",
    stage: "proposal",
    probability: 45,
    expectedMonthlyRevenue: 2600000,
    targetCloseMonth: "2026-07",
    owner: "外食営業チーム",
    blockers: ["厨房オペレーション確認", "物流温度帯の調整"],
    nextStep: "調理負荷テストと配送設計を確認",
    productIds: ["prod-dressing", "prod-soup"],
  },
];

export const demoActivities: ActivitySummary[] = [
  {
    id: "act-aeon-tasting",
    accountId: "acct-aeon",
    accountName: "イオンリテール株式会社",
    type: "tasting",
    subject: "春棚替え向け餃子試食会",
    scheduledFor: "2026-03-15",
    owner: "東日本第1営業部",
    status: "scheduled",
    notes: "冷凍惣菜バイヤーと販促担当が参加予定。競合比較資料を同席させる。",
  },
  {
    id: "act-kokubu-quote",
    accountId: "acct-kokubu",
    accountName: "国分グループ本社株式会社",
    type: "quote",
    subject: "外食向けドレッシング条件見積",
    scheduledFor: "2026-03-12",
    owner: "広域卸営業部",
    status: "needs-follow-up",
    notes: "物流費増分を加味した再見積が必要。",
  },
  {
    id: "act-lawson-review",
    accountId: "acct-lawson",
    accountName: "株式会社ローソン",
    type: "review",
    subject: "テスト販売レビュー共有",
    scheduledFor: "2026-03-11",
    owner: "CVS 営業チーム",
    status: "done",
    notes: "SKU あたりの回転率は基準比 118%。原価条件の再提示が必要。",
  },
  {
    id: "act-rakuten-sample",
    accountId: "acct-rakuten",
    accountName: "楽天マート株式会社",
    type: "sample",
    subject: "EC 限定セットのサンプル配送",
    scheduledFor: "2026-03-18",
    owner: "EC 営業チーム",
    status: "scheduled",
    notes: "レビュー施策用の同梱チラシ案も提出する。",
  },
  {
    id: "act-skylark-visit",
    accountId: "acct-skylark",
    accountName: "株式会社すかいらーくレストランツ",
    type: "visit",
    subject: "厨房オペレーション確認訪問",
    scheduledFor: "2026-03-14",
    owner: "外食営業チーム",
    status: "scheduled",
    notes: "温度帯跨ぎの運用可否を配送チームと確認。",
  },
];